services:
  - type: web
    name: atendedor-2-0
    env: node
    plan: starter
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
